# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: amazon_webapp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='amazon_webapp.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x61mazon_webapp.proto\"\x1a\n\x07\x62uy_req\x12\x0f\n\x07orderid\x18\x01 \x02(\x03\"\x1f\n\x0c\x63\x61ncel_order\x12\x0f\n\x07orderid\x18\x01 \x02(\x03\"B\n\nAWCommands\x12\x15\n\x03\x62uy\x18\x01 \x01(\x0b\x32\x08.buy_req\x12\x1d\n\x06\x63\x61ncel\x18\x02 \x01(\x0b\x32\r.cancel_order')
)




_BUY_REQ = _descriptor.Descriptor(
  name='buy_req',
  full_name='buy_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderid', full_name='buy_req.orderid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=49,
)


_CANCEL_ORDER = _descriptor.Descriptor(
  name='cancel_order',
  full_name='cancel_order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderid', full_name='cancel_order.orderid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=82,
)


_AWCOMMANDS = _descriptor.Descriptor(
  name='AWCommands',
  full_name='AWCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buy', full_name='AWCommands.buy', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cancel', full_name='AWCommands.cancel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=150,
)

_AWCOMMANDS.fields_by_name['buy'].message_type = _BUY_REQ
_AWCOMMANDS.fields_by_name['cancel'].message_type = _CANCEL_ORDER
DESCRIPTOR.message_types_by_name['buy_req'] = _BUY_REQ
DESCRIPTOR.message_types_by_name['cancel_order'] = _CANCEL_ORDER
DESCRIPTOR.message_types_by_name['AWCommands'] = _AWCOMMANDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

buy_req = _reflection.GeneratedProtocolMessageType('buy_req', (_message.Message,), dict(
  DESCRIPTOR = _BUY_REQ,
  __module__ = 'amazon_webapp_pb2'
  # @@protoc_insertion_point(class_scope:buy_req)
  ))
_sym_db.RegisterMessage(buy_req)

cancel_order = _reflection.GeneratedProtocolMessageType('cancel_order', (_message.Message,), dict(
  DESCRIPTOR = _CANCEL_ORDER,
  __module__ = 'amazon_webapp_pb2'
  # @@protoc_insertion_point(class_scope:cancel_order)
  ))
_sym_db.RegisterMessage(cancel_order)

AWCommands = _reflection.GeneratedProtocolMessageType('AWCommands', (_message.Message,), dict(
  DESCRIPTOR = _AWCOMMANDS,
  __module__ = 'amazon_webapp_pb2'
  # @@protoc_insertion_point(class_scope:AWCommands)
  ))
_sym_db.RegisterMessage(AWCommands)


# @@protoc_insertion_point(module_scope)
